[package]
name = "yahtzee-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
enum-map = "2.7.3"
strum = "0.27.2"
strum_macros = "0.27.2"

[[bench]]
name = "solver_bench"
harness = false
